### PR TITLE
Backport from YN

### PR DESCRIPTION
**Pull request by podarok**

### CODE REVIEW

**Comment by sarah-halby** [comment]
@podarok what are the steps to test for the IMX team to test this style update?

**Comment by podarok** [comment]
@shuklina could you provide steps for review, please?

**Comment by shuklina** [comment]
> @shuklina could you provide steps for review, please?

### Steps for review:
- [ ] Go to `/membership-builder`
- [ ] Make sure that there is  `FREE TRIAL`  button near `Join` button
image
- [ ] The path leads to the page with Free Trial form
image

**Comment by podarok** [comment]
@sarah-halby ^^^

**Pull request merged**
